apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-depl
  labels:
    app: express-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"

    spec:
      containers:
      - name: express-api
        image: nthskyradiated/express-ts-api:blue
        ports:
        - containerPort: 8181
        env:
        - name: PORT
          value: "8181"
        - name: MONGO_URI
          value: "mongodb://admin:secret@mongodb-service:27017/collections?authSource=admin"
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: express-api-service
spec:
  selector:
    app: express-api
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
  type: ClusterIP
