apiVersion: apps/v1
kind: Deployment
metadata:
  name: pump-upload-svr-deployment
  labels:
    app: pump-upload-svr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pump-upload-svr
  template:
    metadata:
      labels:
        app: pump-upload-svr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"

    spec:
      containers:
      - name: pump-upload-svr
        image: nthskyradiated/pump-upload-server:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pump-upload-svr-service
spec:
  selector:
    app: pump-upload-svr
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
