# Service for pod1 in the default namespace
apiVersion: v1
kind: Service
metadata:
  name: pod1-svc
  namespace: default
spec:
  selector:
    run: pod1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  clusterIP: None # Headless service for direct pod-to-pod DNS resolution

---
# Service for pod2 in the default namespace
apiVersion: v1
kind: Service
metadata:
  name: pod2-svc
  namespace: default
spec:
  selector:
    run: pod2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  clusterIP: None

---
# Service for pod3 in the staging namespace
apiVersion: v1
kind: Service
metadata:
  name: pod3-svc
  namespace: staging
spec:
  selector:
    run: pod3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  clusterIP: None

---
# Service for pod4 in the dev namespace
apiVersion: v1
kind: Service
metadata:
  name: pod4-svc
  namespace: dev
spec:
  selector:
    run: pod4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  clusterIP: None
