---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: express-api
  namespace: staging
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-api
  progressDeadlineSeconds: 60
  service:
    port: 8181
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
    webhooks:
      - name: load-test
        url: http://loadtester.flagger/
        timeout: 5s
        metadata:
          cmd: "hey -z 10m -q 10 -c 2 http://express-api-canary.staging:8181/"
