---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-api
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pf-api
      istio: monitor
  template:
    metadata:
      labels:
        app: pf-api
        istio: monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: pf-api
          image: nthskyradiated/pf-api-go:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
          - name: MONGODB_URI
            value: mongodb+srv://andypandaan:uEMVUbYqtLwgxeu5@exp-cluster-0.tc1gf.mongodb.net/?retryWrites=true&w=majority&appName=exp-cluster-0
          - name: PORT
            value: "3000"
