---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: express-api
  namespace: staging
spec:
  # service mesh provider can be: kubernetes, istio, appmesh, nginx, gloo
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-api
  progressDeadlineSeconds: 60
  service:
    port: 8080
    portDiscovery: true
  analysis:
    interval: 30s
    # max number of failed checks before rollback
    threshold: 2
    # number of checks to run before rollback
    iterations: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 30s
    webhooks:
      - name: load-test
        url: http://loadtester.istio-system/
        timeout: 5s
        metadata:
          cmd: "hey -z 10m -q 10 -c 2 http://express-api-canary.staging:8080/version"
