apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-depl
  labels:
    app: express-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 4
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"

    spec:
      containers:
      - name: express-api
        image: nthskyradiated/express-ts-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://admin:secret@mongodb-service:27017/collections?authSource=admin"
      imagePullSecrets:
      - name: docker-secret-defaultns
---
apiVersion: v1
kind: Service
metadata:
  name: express-api-service
spec:
  selector:
    app: express-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
