apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: antonputra/043:v0.1.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "250Mi"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: mysecret-volume
          mountPath: /etc/mysecret
          readOnly: true
      volumes:
      - name: mysecret-volume
        secret:
          secretName: mysecret