apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: antonputra/043:v0.1.5
        ports:
        - containerPort: 9090
        env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password