apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/kubedata/
    server: 192.168.1.210
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb-service"
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9216"
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: mongodb
        image: mongodb/mongodb-community-server:latest
        args: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/mongo-keyfile/mkey"]
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: "secret"
        - name: MONGO_REPLICA_SET_NAME
          value: "rs0"
        - name: POD_NAME  # Use the Downward API to inject the Pod name as an env variable
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
          subPathExpr: $(POD_NAME)-db # Use the subPathExpr to inject the Pod name. Not subPath.
        - name: mongodb-keyfile
          mountPath: /data/configdb/mongo-keyfile
          readOnly: true
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
        startupProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30  # Time before starting the first check
          periodSeconds: 10        # Time between probe executions
          failureThreshold: 30     # How many failures before considering the pod as failed
      - name: mongo-sidecar
        image: mongo:latest
        env:
        - name: MONGO_ADMIN_USER
          value: "admin"
        - name: MONGO_ADMIN_PASS
          value: "secret"
        - name: MONGO_REPLICA_SET_NAME
          value: "rs0"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_AUTH_DB
          value: "admin"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - "sh"
        - "-c"
        - |
          check_pod_ready() {
            POD_HOST=$1
            until mongosh --host "$POD_HOST" --username "$MONGO_ADMIN_USER" --password "$MONGO_ADMIN_PASS" --authenticationDatabase "$MONGO_AUTH_DB" --eval 'db.runCommand("ping").ok' --quiet | grep 1; do
              echo "Waiting for $POD_HOST to be ready..."
              sleep 10
            done
          echo "$POD_HOST is ready!"
          }

          # List of MongoDB pod hostnames (without using arrays)
          check_pod_ready "mongodb-0.mongodb-service.default.svc.cluster.local:$MONGO_PORT"
          check_pod_ready "mongodb-1.mongodb-service.default.svc.cluster.local:$MONGO_PORT"
          check_pod_ready "mongodb-2.mongodb-service.default.svc.cluster.local:$MONGO_PORT"

          # Check if the replica set is already initialized
          if mongosh --host "mongodb-0.mongodb-service.default.svc.cluster.local" --username "$MONGO_ADMIN_USER" --password "$MONGO_ADMIN_PASS" --authenticationDatabase "$MONGO_AUTH_DB" --eval 'rs.status().ok' --quiet | grep 1; then
            echo "Replica set already initialized"
          else
            echo "Initializing replica set"
            mongosh --host "mongodb-0.mongodb-service.default.svc.cluster.local" --username "$MONGO_ADMIN_USER" --password "$MONGO_ADMIN_PASS" --authenticationDatabase "$MONGO_AUTH_DB" --eval "
                rs.initiate({
                    _id: '$MONGO_REPLICA_SET_NAME',
                    members: [
                        { _id: 0, host: 'mongodb-0.mongodb-service.default.svc.cluster.local:$MONGO_PORT' },
                        { _id: 1, host: 'mongodb-1.mongodb-service.default.svc.cluster.local:$MONGO_PORT' },
                        { _id: 2, host: 'mongodb-2.mongodb-service.default.svc.cluster.local:$MONGO_PORT' }
                    ]
                });
            "
          fi

          # Keep the sidecar running to monitor replica set status
          while true; do
            sleep 300
          done

      - name: mongo-exporter
        image: bitnami/mongodb-exporter
        args:
        - --mongodb.uri=mongodb://$(MONGODB_INITDB_ROOT_USERNAME):$(MONGODB_INITDB_ROOT_PASSWORD)@mongodb-service.default.svc.cluster.local:27017/admin
        - --collect-all
        ports:
        - containerPort: 9216
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGODB_INITDB_ROOT_PASSWORD
          value: "secret"
        - name: MONGO_REPLICA_SET_NAME
          value: "rs0"
        - name: POD_NAME  # Use the Downward API to inject the Pod name as an env variable
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9216
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 30
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9216
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 30
          failureThreshold: 3
          successThreshold: 1
      volumes:
      - name: mongodb-keyfile
        persistentVolumeClaim:
          claimName: mongodb-keyfile-pvc
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-storage-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-keyfile-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/mongo-keyfile
    server: 192.168.1.210
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-keyfile-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: default
spec:
  clusterIP: None # This makes it a headless service
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
