apiVersion: v1
kind: Service
metadata:
  name: express-api-depl
  namespace: pump-factory
spec:
  ports:
  - nodePort: 32332
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: express-api
    replica: blue
  type: LoadBalancer
