apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-green
  namespace: pump-factory
  labels:
    app: express-api
spec:
  strategy:
  replicas: 2
  selector:
    matchLabels:
      app: express-api
      replica: green
  template:
    metadata:
      labels:
        app: express-api
        replica: green
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"

    spec:
      containers:
      - name: express-api
        image: nthskyradiated/express-ts-api:green
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: mongodb+srv://andypandaan:uEMVUbYqtLwgxeu5@exp-cluster-0.tc1gf.mongodb.net/?retryWrites=true&w=majority&appName=exp-cluster-0
        - name: PORT
          value: "8080"
      imagePullSecrets:
      - name: docker-secret

