apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: monitoring
spec:
  serviceAccount: kubectl-sa
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "20000"]
