{
 "title": "Latency & Availability & RPS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"monitoring/pf-api\",status!~\"[4-5].*\"}[1m])) / sum(rate(request_duration_seconds_count{job=\"monitoring/pf-api\"}[1m]))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Latency - p95",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket{job=\"monitoring/pf-api\"}[1m])) by (le))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count{job=\"monitoring/pf-api\"}[1m]))",
     "legendFormat": "All"
    }
   ]
  }
 ]
}