---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pf-api-primary
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: pf-api
      type: primary
  podMetricsEndpoints:
    - port: http
      path: metrics
