---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pf-api-canary
  namespace: monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: pf-api
      type: canary
  podMetricsEndpoints:
    - port: http
      path: metrics
