---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dockerhub-pf-argocd-dev
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgCtEgwUpkEgGX0zZWhGVaTtjwJBanC/GfdIUNLEo7YWG1ZOiSwwBYV07ovkzb58/gPA+TLvyhsbLKgBY0JsDdhQBw1wxYq2TtZdRiU7vZbPX05nLg8+/Z7vM5s/zhTCNSxVH7wjsI6y37HklBbxPgwisHDO9t3XxRrSVBzcYzbxf1iyfjQk6kjiCOVj/Jh5xuPjFHUY9LTKTN6wTttCFzR5l4tRQUKZKSRNACPY5o5IRDOoRR/PgtAY6I8VWbODlIIg71QQ8Jxj7rPm9L8Km58b+VCIYolOozxH5qH9qDTwqmYm0HTCSGKdnuhJn/iAZrTfohytF40E+ZVwNQR3O0EIXVDMrsGQNGHeo4J5Nrvf3P3EhBA5Mw0wgguzDsNLdz1OWFYI4aenvDd8M8RktkYTPF5lBXPQsv6o9kZ5ZUA7SaoAxzMLtKuuCHovEdunsBfSI4OV6z+wsjQUQnwllKyGISXD/L2yhr7hNC4Nxq7kj88NWg7CJfZvMZg81iTbiO5duUHFZyV4umG0t6sS0FByPyzYOoKjvbKsSj1TFkJkpML0CmyiZyPVIN4uNoq0P4RVWa+ahC558KZEId9/OWq1wa2yCLarr7xjlNHg622xhvKDAH7TYMzXmnSPBwm5KPEhjngp6Ca9vqPUZiTdT7FlunMssOYKqwbdLHI9Vh/vnvWcmkiXi7w8gdS1T/oLUxy4qGS/R71THWs3ALqRSVkPhlttaSEf3JDWYQMzk1oUHy/+rvt68HaU1RjP0d7Hya+mlO1dNYH9SYreXiyvoFOMQq4Om5S/oCTBjv87pBjb9vrIk5x6VDU0JZtvp4jBtkeNOgBwthK0yMs3r+m/nFLa+EabEChXtXnaGSA7tqDq6iljqTY7WeLbSVjV/UvwXUz8+7eC3jrZlXEiilBteOpJ+oWsp0C2ZGrnlAdMkkxJSLLBkQ/gXg7b06MGG3D2EGTxedSDGgRgHfo1/q6CEpSbciM1n25U9zFQ9iSkQAAbxtRHKuvm97dqivs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dockerhub-pf-argocd-dev
      namespace: dev
    type: kubernetes.io/dockerconfigjson
