apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJudGhza3lyYWRpYXRlZCIsInBhc3N3b3JkIjoiZGNrcl9wYXRfcnBJbXZaZUo1UUZGMWRtRGdBNk5wb0ZaY1BRIiwiZW1haWwiOiJhbmR5LnBhbmRhYW5Ab3V0bG9vay5jb20iLCJhdXRoIjoiYm5Sb2MydDVjbUZrYVdGMFpXUTZaR05yY2w5d1lYUmZjbkJKYlhaYVpVbzFVVVpHTVdSdFJHZEJOazV3YjBaYVkxQlIifX19
kind: Secret
metadata:
  creationTimestamp: "2025-01-20T16:22:03Z"
  name: docker-secret-defaultns
  namespace: default
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: docker-secret-defaultns
    uid: 37f90017-e1e0-4915-9288-e77632a584c6
  resourceVersion: "1524907"
  uid: 64ff6ee3-af2d-4181-bbe3-27fd1624530e
type: kubernetes.io/dockerconfigjson
